# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MapEditor.ui'
#
# Created: Sat Feb 16 00:56:17 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MapEditor(object):
    def setupUi(self, MapEditor):
        MapEditor.setObjectName("MapEditor")
        MapEditor.resize(1280, 720)
        self.centralwidget = QtGui.QWidget(MapEditor)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftcontainer = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftcontainer.sizePolicy().hasHeightForWidth())
        self.leftcontainer.setSizePolicy(sizePolicy)
        self.leftcontainer.setMinimumSize(QtCore.QSize(200, 0))
        self.leftcontainer.setMaximumSize(QtCore.QSize(200, 16777215))
        self.leftcontainer.setObjectName("leftcontainer")
        self.verticalLayout = QtGui.QVBoxLayout(self.leftcontainer)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtGui.QScrollArea(self.leftcontainer)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 180, 659))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(180, 16777215))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.leftcontainer)
        MapEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MapEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTelemetry = QtGui.QMenu(self.menubar)
        self.menuTelemetry.setObjectName("menuTelemetry")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MapEditor.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MapEditor)
        self.statusbar.setObjectName("statusbar")
        MapEditor.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MapEditor)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(MapEditor)
        self.actionAbout.setObjectName("actionAbout")
        self.actionKills = QtGui.QAction(MapEditor)
        self.actionKills.setObjectName("actionKills")
        self.actionDeaths = QtGui.QAction(MapEditor)
        self.actionDeaths.setObjectName("actionDeaths")
        self.actionJumps = QtGui.QAction(MapEditor)
        self.actionJumps.setObjectName("actionJumps")
        self.actionLoad = QtGui.QAction(MapEditor)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtGui.QAction(MapEditor)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTelemetry.addAction(self.actionKills)
        self.menuTelemetry.addAction(self.actionDeaths)
        self.menuTelemetry.addAction(self.actionJumps)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTelemetry.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MapEditor)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("activated()"), MapEditor.close)
        QtCore.QMetaObject.connectSlotsByName(MapEditor)

    def retranslateUi(self, MapEditor):
        MapEditor.setWindowTitle(QtGui.QApplication.translate("MapEditor", "MapEditor", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MapEditor", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTelemetry.setTitle(QtGui.QApplication.translate("MapEditor", "Telemetry", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MapEditor", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MapEditor", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MapEditor", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKills.setText(QtGui.QApplication.translate("MapEditor", "Kills", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeaths.setText(QtGui.QApplication.translate("MapEditor", "Deaths", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJumps.setText(QtGui.QApplication.translate("MapEditor", "Jumps", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("MapEditor", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MapEditor", "Save", None, QtGui.QApplication.UnicodeUTF8))

